/* emit_rl_world.c - the world build: prologue, parameters, payload and
 * world construction, and the reset draws. */
#include "emit_rl_internal.h"

static int rl_emit_payload_build_(FILE *out, const RlModel *m,
                                  const KflcExprCtx *ctx, KflcDiag *diag);

int rl_emit_prologue(FILE *out, const RlModel *m,
                             const KflcNode *form, KflcDiag *diag)
{
    fprintf(out,
        "/* AUTO-GENERATED by kflc. DO NOT EDIT BY HAND.\n"
        " * Source form: %s\n"
        " *\n"
        " * Reinforcement learning environment core. One translation\n"
        " * unit, two artifacts: compiled with KFLC_RL_BATCH_MAIN it is\n"
        " * the batch executable; compiled as a shared object it exports\n"
        " * exactly the k26rl_ stepping surface. Batch mode drives the\n"
        " * same create/step/reset code through the same functions, so\n"
        " * the two entries are bit-identical by construction. */\n\n",
        form->name ? form->name : "FORM");

    fputs(
        "#include <k26astro_rt/world.h>\n"
        "#include <k26astro_rt/observer.h>\n"
        "#include <k26astro_rt/world_rng.h>\n"
        "#include <k26astro_rt/conservation_ledger.h>\n"
        "#include <k26astro_grav/grav.h>\n"
        "#include <k26astro_grav/ias15.h>\n"
        "#include <k26astro_grav/perturb.h>\n"
        "#include <k26astro_body/body.h>\n"
        "#include <k26astro_core/pos.h>\n"
        "#include <k26astro_vehicle/vehicle.h>\n"
        "#include <k26astro_att/att.h>\n", out);
    if (m->n_colliders > 0) {
        fputs("#include <k26astro_coll/coll.h>\n", out);
    }
    if (rl_has_relative_observe(m)) {
        /* Only a program that declares a relative observe pulls in the
         * proximity library, for the reason the field model is
         * conditional below: a dependency follows a declaration. */
        fputs("#include <k26astro_prox/prox.h>\n", out);
    }
    /* Likewise the defense tier: a program that declares no payload
     * acquires no archive on its link line. The kind registry is
     * included beside them because the payload base carries its tag
     * and this artifact sets it from the same registry the libraries
     * read it from. */
    if (rl_n_pay_kind(m, RL_PAY_INFOSTATE) > 0) {
        fputs("#include <k26astro_infostate/infostate.h>\n"
              "#include <k26astro_infostate/infostate_consts.h>\n"
              "#include <k26astro_core/epoch.h>\n", out);
    }
    /* The signature and counter-detection routines live in the
     * detection library, and a jammer engagement reads both: the radar
     * cross-section of the craft it protects, and the range at which
     * the victim's own infrared observer sees the jammer's emission. So
     * a program with a jammer takes that header whether or not it
     * declares a detection payload of its own. */
    if (rl_n_detect(m) > 0 || rl_n_pay_kind(m, RL_PAY_JAMMER) > 0) {
        fputs("#include <k26astro_detect/detect.h>\n", out);
    }
    /* The countermeasure library. Its constants header carries the
     * discriminator-regime enumeration and the default dipole
     * cross-section, both of which a detection payload's own keys name,
     * so a program with a detection payload takes the constants even
     * when it declares no countermeasure. Nothing is linked for that:
     * the constants are compile-time and the archive follows the
     * payload rather than the header. */
    if (rl_n_pay_kind(m, RL_PAY_DECOY) > 0 ||
        rl_n_pay_kind(m, RL_PAY_JAMMER) > 0 ||
        rl_n_chaff(m) > 0) {
        fputs("#include <k26astro_softkill/softkill.h>\n", out);
    } else if (rl_n_detect(m) > 0) {
        fputs("#include <k26astro_softkill/softkill_consts.h>\n", out);
    }
    if (rl_n_pay_kind(m, RL_PAY_IMPACTOR) > 0) {
        fputs("#include <k26astro_impactor/impactor.h>\n"
              "#include <k26astro_impactor/energy_coupling.h>\n"
              "#include <k26astro_impactor/swarm.h>\n"
              "#include <k26astro_impactor/terminal_phase.h>\n", out);
    }
    if (rl_n_pay_kind(m, RL_PAY_LASER) > 0) {
        fputs("#include <k26astro_laser/laser.h>\n", out);
    }
    /* The mathematical constants the three closed-form models read,
     * pulled in once for whichever of them the program declares. */
    if (rl_n_detect(m) > 0 || rl_n_effector(m) > 0) {
        fputs("#include <k26astro_core/consts.h>\n", out);
    }
    if (m->n_payloads > 0) {
        fputs("#include <k26astro_defense/defense_kinds.h>\n"
              "#include <k26astro_vehicle/payload.h>\n", out);
    }
    if (rl_n_sensed(m) > 0) {
        /* Only a program that declares a sensor pulls in the
         * imperfection layer, for the reason the field model and the
         * proximity library are conditional: a dependency follows a
         * declaration, and a program that declares no sensor must not
         * acquire a new archive on its link line. */
        fputs("#include <k26sense.h>\n", out);
    }
    if (m->n_torquers > 0) {
        /* Only a program that declares a magnetorquer pulls in the
         * field model, which is Fortran-backed: the dependency is a
         * consequence of a declaration and not of the tier existing. */
        fputs("#include <k26astro_geomag/geomag.h>\n"
              "#include <k26astro_body/rotation_model.h>\n", out);
    }
    if (m->n_plans > 0) {
        /* A world that emits a plan writes the file through the
         * unbuffered calls, so that an episode end costs no
         * allocation; a stream would allocate its buffer. Only such a
         * program takes these headers. */
        fputs("#include \"k26rl_ref.h\"\n"
              "#include <fcntl.h>\n"
              "#include <unistd.h>\n", out);
    }
    fputs(
        "#include \"k26rl_env.h\"\n"
        "#include \"k26rl_episode.h\"\n"
        "#include \"k26rl_tap.h\"\n"
        "#include \"k26rng.h\"\n"
        "\n"
        "#include <stdint.h>\n"
        "#include <stdio.h>\n"
        "#include <stdlib.h>\n"
        "#include <string.h>\n"
        "#include <cmath>\n"
        "\n", out);

    /* Program geometry. */
    fprintf(out,
        "#define KFLRL_N_BODIES %d\n"
        "#define KFLRL_OBS_TOTAL %du\n"
        "#define KFLRL_ACT_TOTAL %du\n"
        "#define KFLRL_N_RESET %d\n"
        "#define KFLRL_N_DR %d\n"
        "#define KFLRL_N_REC %d\n"
        "#define KFLRL_N_WSCAL %d\n"
        "#define KFLRL_HAS_TERMINATED %d\n"
        "#define KFLRL_N_VEHICLES %d\n"
        "#define KFLRL_N_AGENTS %d\n"
        "#define KFLRL_MAGIC 0x4b524c45u\n"
        "\n",
        m->n_bodies, rl_obs_total(m->observes, m->n_observes),
        m->n_actions,
        m->n_resets, m->n_dr, m->n_resets + m->n_dr,
        m->n_wscal, m->terminated_when ? 1 : 0,
        rl_n_vehicles(m), m->agent_count);

    /* Per agent, in agent-index order: the observation and action
     * slice it owns. Contiguous by construction, since channels
     * allocate in source order within a block and blocks in source
     * order, so the concatenation over agents is the whole vector. */
    fputs("static const uint32_t kflrl_agent_slices_[KFLRL_N_AGENTS][4] = {\n",
          out);
    for (int i = 0; i < m->agent_count; i++) {
        const RlAgent *a = &m->agents[i];
        fprintf(out, "    { %du, %du, %du, %du },\n",
                (unsigned)a->obs_off, (unsigned)a->obs_count,
                (unsigned)a->act_off, (unsigned)a->act_count);
    }
    fputs("};\n\n", out);

    /* Domain-randomisation record tags, ascending (class, channel):
     * reset-state entries (class 0x0001) then domain-randomisation
     * entries (class 0x0002). */
    fputs("#if KFLRL_N_REC > 0\n"
          "static const uint32_t kflrl_dr_tags_[KFLRL_N_REC] = {", out);
    for (int i = 0; i < m->n_resets; i++) {
        fprintf(out, "%s0x%08xu", i ? ", " : " ",
                (0x0001u << 16) | (unsigned)i);
    }
    for (int i = 0; i < m->n_dr; i++) {
        fprintf(out, "%s0x%08xu", (i || m->n_resets) ? ", " : " ",
                (0x0002u << 16) | (unsigned)m->dr[i].channel);
    }
    fputs(" };\n#endif\n\n", out);

    /* Observation channel names, source order, one entry per
     * component of each observe-as statement. */
    if (m->n_observes > 0) {
        fputs("static const char *const kflrl_obs_names_"
              "[KFLRL_OBS_TOTAL] = {\n", out);
        for (int i = 0; i < m->n_observes; i++) {
            for (int c = 0; c < rl_observe_width(m->observes[i]); c++) {
                /* A published name that would not fit the entry is
                 * refused here rather than truncated in the artifact.
                 * With one agent the declarable bound and the entry
                 * are sized so this cannot fire (internal.h states
                 * that arithmetic); with more than one the qualifier
                 * is what can overflow it. */
                char pub[KFLC_OBS_NAME_MAX + 1];
                if (rl_obs_pub_name(m, i, c, pub, sizeof pub, diag)) {
                    return 1;
                }
                fprintf(out, "    \"%s\",\n", pub);
            }
        }
        fputs("};\n\n", out);

        /* The mode each channel's observe declared, published per
         * channel so a consumer reads it without reconstructing
         * observe grouping. */
        fputs("static const uint16_t kflrl_obs_modes_"
              "[KFLRL_OBS_TOTAL] = {\n", out);
        for (int i = 0; i < m->n_observes; i++) {
            uint16_t md = rl_observe_mode(m->observes[i]);
            for (int c = 0; c < rl_observe_width(m->observes[i]); c++) {
                fprintf(out, "    %u,\n", (unsigned)md);
            }
        }
        fputs("};\n\n", out);

        /* What each channel is, and which channel it is paired with.
         * A program declaring no sensor publishes every channel as
         * measured and unpaired, which is what it is: the value the
         * simulation produced, with nothing between. */
        fputs("static const uint16_t kflrl_obs_source_"
              "[KFLRL_OBS_TOTAL] = {\n", out);
        for (int i = 0; i < m->n_observes; i++) {
            int w = rl_observe_base_width(m->observes[i]);
            int t = rl_observe_has_truth(m->observes[i]);
            for (int c = 0; c < w; c++) {
                fprintf(out, "    %u,\n",
                        (unsigned)K26RL_OBS_SOURCE_MEASURED);
            }
            if (!t) continue;
            for (int c = 0; c < w; c++) {
                fprintf(out, "    %u,\n", (unsigned)K26RL_OBS_SOURCE_TRUTH);
            }
        }
        fputs("};\n\nstatic const uint32_t kflrl_obs_pair_"
              "[KFLRL_OBS_TOTAL] = {\n", out);
        for (int i = 0; i < m->n_observes; i++) {
            int off = rl_obs_offset(m->observes, i);
            int w   = rl_observe_base_width(m->observes[i]);
            int t   = rl_observe_has_truth(m->observes[i]);
            for (int c = 0; c < w; c++) {
                if (t) fprintf(out, "    %uu,\n", (unsigned)(off + w + c));
                else   fprintf(out, "    %uu,\n",
                               (unsigned)K26RL_OBS_PAIR_NONE);
            }
            if (!t) continue;
            for (int c = 0; c < w; c++) {
                fprintf(out, "    %uu,\n", (unsigned)(off + c));
            }
        }
        fputs("};\n\n", out);
    }

    /* Body names, declaration order, which is the order the body-state
     * getter returns and the order the body-name tags index. */
    if (m->n_bodies > 0) {
        fputs("static const char *const kflrl_body_names_"
              "[KFLRL_N_BODIES] = {\n", out);
        for (int i = 0; i < m->n_bodies; i++) {
            fprintf(out, "    \"%s\",\n",
                    m->bodies[i].body->name ? m->bodies[i].body->name : "?");
        }
        fputs("};\n\n", out);
    }

    /* Vehicle slot to body index, in the order the vehicles are
     * created, so the step can find each vehicle's own body and the
     * body it is attracted by without searching. */
    {
        int n_v = 0;
        for (int i = 0; i < m->n_bodies; i++) {
            if (!rl_body_has_assembly(m, i)) continue;
            if (n_v == 0) {
                fputs("static const int kflrl_vehicle_body_[] = {\n", out);
            }
            fprintf(out, "    %d,\n", i);
            n_v++;
        }
        if (n_v > 0) fputs("};\n\n", out);
    }

    /* ---- The collider set ---------------------------------------- *
     *
     * Counts and shapes are fixed at compile time, so the per-step
     * working set is a fixed-size array and the loops are over
     * constants. The primitives are already in their bodies' frames;
     * only the rotation into the world frame is left to the step, and
     * that is one quaternion per body rather than one per primitive.
     */
    fprintf(out, "#define KFLRL_N_COLL %d\n", m->n_colliders);
    /* The contact block is one entry per collidable body, and at
     * least one, so that a program with no vehicles still allocates
     * something a pointer check can be made against. */
    fprintf(out, "#define KFLRL_OBS_NAME_MAX %d\n", KFLC_OBS_NAME_MAX);
    if (rl_emit_sensors(out, m, diag)) return 1;
    fprintf(out, "#define KFLRL_N_CONTACT %d\n\n",
            m->n_veh > 0 ? m->n_veh : 1);
    fputs(
"/* What a contact observe form publishes: whether this transition\n"
" * contained one, at what fraction of the control period the first\n"
" * one occurred, and how fast the pair was closing along the contact\n"
" * normal when it did. Zero on a transition with no contact, which\n"
" * is what makes the three channels readable without a fourth saying\n"
" * whether the other three mean anything. */\n"
"typedef struct {\n"
"    double hit;\n"
"    double fraction;\n"
"    double speed;\n"
"} KflrlContact;\n\n", out);
    /* The port latch is per port rather than per body. A body may
     * carry several docking interfaces and take part in several
     * pairings, and a latch shared across them would publish one
     * pairing's residuals under another pairing's name. */
    fprintf(out, "#define KFLRL_N_PLAT %d\n\n",
            m->n_ports > 0 ? m->n_ports : 1);
    fputs(
"/* What a port observe form publishes on a transition whose contact\n"
" * was between two docking interfaces: which port this one met,\n"
" * whether the pair satisfied every condition of the declared\n"
" * envelope, and the residuals the test was given.\n"
" *\n"
" * They are latched because the test is a statement about the instant\n"
" * of contact, and by the end of the transition the resolution has\n"
" * already removed the relative velocity the test read.\n"
" *\n"
" * `partner` is what makes the latch a fact about a pairing rather\n"
" * than about a port: a form publishes the latched values only when\n"
" * the contact was with the port that form is paired against, and\n"
" * reads the state as it stands otherwise. */\n"
"typedef struct {\n"
"    double hit;\n"
"    int    partner;       /* port index met, -1 when none */\n"
"    double captured;\n"
"    double axial;\n"
"    double lateral;\n"
"    double pitchyaw;\n"
"    double roll;\n"
"    double v_axial;\n"
"    double v_lateral;\n"
"    double v_pitchyaw;\n"
"    double v_roll;\n"
"    double v_cg;\n"
"} KflrlPortLatch;\n\n", out);
    /* Capacity one less than the vehicle count. Every join gives one
     * body a leader and a body follows at most one leader, so a world
     * of n vehicles admits at most n-1 joins and the table can never
     * be the thing that refuses one. */
    fprintf(out, "#define KFLRL_N_JOINS %d\n\n",
            m->n_veh > 1 ? m->n_veh - 1 : 1);
    fputs(
"/* One join, formed by a capture.\n"
" *\n"
" * A capture is not a resolution the environment declares. It takes\n"
" * precedence over the declared one, because a programme told its\n"
" * craft is docked and then shown it flung away has been told two\n"
" * things that cannot both be true; and it does not merely stop the\n"
" * pair, it makes them one body.\n"
" *\n"
" * A join attaches a follower to a leader. The follower brings\n"
" * whatever is already joined beneath it, so a chain of them is one\n"
" * composite: mass summed over its members, centre of mass the\n"
" * mass-weighted mean of theirs, inertia the sum of theirs carried to\n"
" * that centre by the parallel-axis theorem. A body follows at most\n"
" * one leader, which is what makes the set of joins a forest and the\n"
" * composite well defined.\n"
" *\n"
" * The chain is projected back onto one rigid motion at the end of\n"
" * every sub-advance: each follower is placed from its leader at the\n"
" * frozen offset, and the members' momenta are summed and turned back\n"
" * into one velocity and one rate. Projecting rather than slaving is\n"
" * what keeps a thruster on any member accelerating the whole, which\n"
" * is what a task that continues past docking needs.\n"
" *\n"
" * A member's colliders leave the pass against the other members of\n"
" * its own chain and stay live against every other body, so carried\n"
" * cargo still reports what it runs into. */\n"
"typedef struct {\n"
"    int     active;\n"
"    int     leader;       /* vehicle slot carrying the follower */\n"
"    int     follower;\n"
"    int     port_leader;  /* port index on the leader, -1 when none */\n"
"    int     port_follower;\n"
"    K26V3   offset;       /* follower origin, leader body frame */\n"
"    K26Quat rel;          /* follower attitude = leader's times this */\n"
"} KflrlJoin;\n\n", out);
    if (m->n_colliders > 0) {
        fputs("static const K26AstroCollShape kflrl_coll_[] = {\n", out);
        for (int i = 0; i < m->n_colliders; i++) {
            const RlCollider *c = &m->colliders[i];
            fprintf(out,
                "    { (K26AstroCollKind)%d, { %.17g, %.17g, %.17g },\n"
                "      { { %.17g, %.17g, %.17g }, { %.17g, %.17g, %.17g },\n"
                "        { %.17g, %.17g, %.17g } },\n"
                "      { %.17g, %.17g, %.17g } },\n",
                c->kind, c->centre[0], c->centre[1], c->centre[2],
                c->axis[0][0], c->axis[0][1], c->axis[0][2],
                c->axis[1][0], c->axis[1][1], c->axis[1][2],
                c->axis[2][0], c->axis[2][1], c->axis[2][2],
                c->half[0], c->half[1], c->half[2]);
        }
        fputs("};\n\n", out);

        /* Where each vehicle's primitives begin and how many it has,
         * so the pass slices one array rather than following
         * pointers. */
        fputs("static const int kflrl_coll_first_[] = {\n", out);
        for (int v = 0; v < m->n_veh; v++) {
            int first = -1;
            for (int i = 0; i < m->n_colliders; i++) {
                if (m->colliders[i].veh == v && first < 0) first = i;
            }
            fprintf(out, "    %d,\n", first < 0 ? 0 : first);
        }
        fputs("};\n\nstatic const int kflrl_coll_count_[] = {\n", out);
        for (int v = 0; v < m->n_veh; v++) {
            int n = 0;
            for (int i = 0; i < m->n_colliders; i++) {
                if (m->colliders[i].veh == v) n++;
            }
            fprintf(out, "    %d,\n", n);
        }
        fputs("};\n\n", out);

        fputs("static const double kflrl_veh_bound_[] = {\n", out);
        for (int v = 0; v < m->n_veh; v++) {
            fprintf(out, "    %.17g,\n", m->veh_bound[v]);
        }
        fputs("};\n\n", out);
    }

    if (rl_emit_payload_tables(out, m)) return 1;

    /* ---- Docking ports ---------------------------------------- *
     *
     * One entry per port that named a capture envelope. `shape` is
     * the index, within its own vehicle's collider slice, of the
     * mating plane the assembly reader built from the envelope's
     * published diameter, which is what tells a contact at the
     * docking interface from a contact anywhere else on the craft.
     *
     * The envelope arrives here already in SI. Its printed figures
     * and the single conversion that turns them into these constants
     * live in the compiler's capture table, so a citation stays exact
     * and the arithmetic that changed the units is in one place
     * rather than spread through the artifact.
     */
    fprintf(out, "#define KFLRL_N_PORTS %d\n\n", m->n_ports);
    if (m->n_ports > 0) {
        fputs(
"typedef struct {\n"
"    int                  veh;\n"
"    int                  shape;\n"
"    K26V3                com;\n"
"    K26AstroCollPort     geom;\n"
"    K26AstroCollEnvelope env;\n"
"} KflrlPort;\n\n", out);
        fputs("static const KflrlPort kflrl_ports_[] = {\n", out);
        for (int i = 0; i < m->n_ports; i++) {
            const RlPort *pt = &m->ports[i];
            fprintf(out,
                "    { %d, %d,\n"
                "      { %.17g, %.17g, %.17g },\n"
                "      { { %.17g, %.17g, %.17g },\n"
                "        { { %.17g, %.17g, %.17g }, { %.17g, %.17g, %.17g },\n"
                "          { %.17g, %.17g, %.17g } } },\n"
                "      { %.17g, %.17g, %.17g, %.17g, %.17g,\n"
                "        %.17g, %.17g, %.17g } },\n",
                pt->veh, pt->coll,
                pt->com[0], pt->com[1], pt->com[2],
                pt->at[0], pt->at[1], pt->at[2],
                pt->basis[0][0], pt->basis[0][1], pt->basis[0][2],
                pt->basis[1][0], pt->basis[1][1], pt->basis[1][2],
                pt->basis[2][0], pt->basis[2][1], pt->basis[2][2],
                pt->axial_rate_min, pt->axial_rate_max, pt->lateral_rate,
                pt->pitchyaw_rate, pt->roll_rate,
                pt->lateral, pt->pitchyaw, pt->roll);
        }
        fputs("};\n\n", out);
        fputs(
"/* One body as the port geometry takes it, at rest over a zero\n"
" * interval: the residuals a port observe publishes between contacts\n"
" * are of the state as it stands, so both endpoints of the interval\n"
" * are the same state and the fraction asked for is zero. */\n"
"static void kflrl_port_snap_(const K26AstroBody *b, K26V3 com, K26V3 pos,\n"
"                             K26AstroCollBody *out)\n"
"{\n"
"    memset(out, 0, sizeof *out);\n"
"    out->pos0 = pos;\n"
"    out->pos1 = pos;\n"
"    out->orientation = b->attitude;\n"
"    out->vel0 = b->vel;\n"
"    out->vel1 = b->vel;\n"
"    out->omega = b->omega;\n"
"    out->mass = b->mass;\n"
"    out->com_offset = com;\n"
"}\n\n"
"/* Whether the two ports of one pairing are held by an active join.\n"
" * This is the standing state a `full` port observe publishes, which\n"
" * the capture channel is not: that one is a pulse on the step whose\n"
" * contact met every condition, and it is clear on every step after\n"
" * it however long the two stay mated. */\n"
"static double kflrl_ports_joined_(const KflrlJoin *jn, int pa, int pb)\n"
"{\n"
"    if (!jn) return 0.0;\n"
"    for (int k = 0; k < KFLRL_N_JOINS; k++) {\n"
"        if (!jn[k].active) continue;\n"
"        if ((jn[k].port_leader == pa && jn[k].port_follower == pb) ||\n"
"            (jn[k].port_leader == pb && jn[k].port_follower == pa)) {\n"
"            return 1.0;\n"
"        }\n"
"    }\n"
"    return 0.0;\n"
"}\n\n", out);
    }

    /* Assembly identity, per body that carries one. The assembly is
     * read again here rather than passed across from the body
     * emitter: a digest is a pure function of the asset bytes, so two
     * reads agree by construction, and the alternative is a naming
     * contract between two files for no gain. Bodies without an
     * assembly appear in neither table and publish neither tag. */
    {
        int n_asm = 0;
        for (int i = 0; i < m->n_bodies; i++) {
            const KflcNode *b = m->bodies[i].body;
            KflcArena *ar = kflc_arena_create();
            if (!ar) return 1;
            KflcAssembly *asmb = NULL;
            if (kflc_assembly_for_body(b, diag->path, ar, diag, &asmb)) {
                kflc_arena_release(ar);
                return 1;
            }
            if (!asmb) { kflc_arena_release(ar); continue; }
            if (n_asm == 0) {
                fputs("static const struct {\n"
                      "    uint32_t body;\n"
                      "    const char *name;\n"
                      "    uint8_t digest[32];\n"
                      "} kflrl_assemblies_[] = {\n", out);
            }
            fprintf(out, "    { %d, \"%s\", {", i, asmb->name);
            for (int k = 0; k < KFLC_ASM_DIGEST; k++) {
                fprintf(out, "%s0x%02x", k ? "," : "",
                        (unsigned)asmb->digest[k]);
            }
            fputs("} },\n", out);
            n_asm++;
            kflc_arena_release(ar);
        }
        if (n_asm > 0) fputs("};\n", out);
        fprintf(out, "#define KFLRL_N_ASSEMBLIES %d\n\n", n_asm);
    }

    /* Draw helpers: draw index 0 at (class, channel, environment,
     * episode); a parameter consumes exactly one draw, and drawing is
     * a pure function of its coordinates. normal(mu, sigma) is the
     * affine transform of the standard normal primitive. */
    fputs(
        "static double kflrl_uniform_(K26RngKey _kfl_key, uint16_t cls,\n"
        "                             uint16_t ch, uint32_t envi,\n"
        "                             uint32_t ep, double a, double b)\n"
        "{\n"
        "    K26RngCoords c;\n"
        "    c.stream = cls; c.channel = ch;\n"
        "    c.environment = envi; c.episode = ep; c.draw = 0;\n"
        "    return k26rng_uniform(_kfl_key, c, a, b);\n"
        "}\n"
        "\n"
        "static double kflrl_normal_(K26RngKey _kfl_key, uint16_t cls,\n"
        "                            uint16_t ch, uint32_t envi,\n"
        "                            uint32_t ep, double mu, double sigma)\n"
        "{\n"
        "    K26RngCoords c;\n"
        "    c.stream = cls; c.channel = ch;\n"
        "    c.environment = envi; c.episode = ep; c.draw = 0;\n"
        "    return mu + sigma * k26rng_normal(_kfl_key, c);\n"
        "}\n"
        "\n", out);

    /* Body indices as add_body returns them; worlds are built by the
     * same code in the same order, so the mapping is identical across
     * environments and captured once. */
    /* The seed a world's own stateful generator takes for one
     * environment and episode. It is a counter draw at the
     * imperfection layer's reserved channel, which that layer never
     * allocates to a model; the two numbers are the library's own
     * constants, read at compile time so that a program declaring no
     * sensor carries no dependency on it, and an artifact gate checks
     * the emitted seed against the library's function. */
    fprintf(out,
        "static uint64_t kflrl_world_seed_(K26RngKey _kfl_key,\n"
        "                                  uint32_t e, uint32_t ep)\n"
        "{\n"
        "    K26RngCoords c;\n"
        "    c.stream = 0x%04xu; c.channel = 0x%04xu;\n"
        "    c.environment = e; c.episode = ep; c.draw = 0u;\n"
        "    return k26rng_u64(_kfl_key, c);\n"
        "}\n\n",
        (unsigned)K26SENSE_CLASS_SENSOR,
        (unsigned)K26SENSE_CHANNEL_WORLD_SEED);

    fputs("static int kflrl_body_idx_[KFLRL_N_BODIES > 0 ? "
          "KFLRL_N_BODIES : 1];\n\n", out);
    return 0;
}

/* Form-argument globals, exactly the batch emitter's shape, so RL
 * expressions and the batch CLI read the same storage. */

void rl_emit_form_args(FILE *out, const KflcNode *form)
{
    int nargs = 0;
    for (const KflcNode *c = form->children; c; c = c->next) {
        if (c->kind == KFLN_ARG) nargs++;
    }
    if (nargs == 0) return;

    for (const KflcNode *c = form->children; c; c = c->next) {
        if (c->kind != KFLN_ARG || c->position.kind != KFLV_STR) continue;
        int ro = (c->flags & KFL_NF_READONLY) ? 1 : 0;
        fprintf(out, "static %schar kfl_arg_%s_buf[2048] = ",
                ro ? "const " : "", c->name);
        rl_emit_string_literal(out, c->position.u.s ? c->position.u.s : "");
        fputs(";\n", out);
    }
    fputs("extern \"C\" {\n", out);
    for (const KflcNode *c = form->children; c; c = c->next) {
        if (c->kind != KFLN_ARG) continue;
        int ro = (c->flags & KFL_NF_READONLY) ? 1 : 0;
        if (c->position.kind == KFLV_STR) {
            fprintf(out, "    const char *%skfl_arg_%s = kfl_arg_%s_buf;\n",
                    ro ? "const " : "", c->name, c->name);
        } else if (c->position.kind == KFLV_FLOAT) {
            fprintf(out, "    %sdouble kfl_arg_%s = %.17g;\n",
                    ro ? "const " : "", c->name, c->position.u.f);
        } else if (c->position.kind == KFLV_INT &&
                   (c->position.u.i < 0 || c->position.u.i > 1)) {
            fprintf(out, "    %sint kfl_arg_%s = %ld;\n",
                    ro ? "const " : "", c->name, c->position.u.i);
        } else {
            int dflt = (c->position.kind == KFLV_INT)
                       ? (int)c->position.u.i : 0;
            fprintf(out, "    %sbool kfl_arg_%s = %s;\n",
                    ro ? "const " : "", c->name, dflt ? "true" : "false");
        }
    }
    fputs("}\n\n", out);
}

/* User fns at form scope, mirroring the batch emitter so calls from
 * world prefixes and reinforcement learning expressions resolve. */

int rl_emit_user_fns(FILE *out, const KflcNode *form,
                             KflcArena *arena, KflcExprFn *user_fn_arr,
                             int n_user_fns, KflcDiag *diag)
{
    for (const KflcNode *fn = form->children; fn; fn = fn->next) {
        if (fn->kind != KFLN_FN) continue;
        const char *ret_cxx = kflc_type_cxx(fn->type, fn->type_subtype);
        if (!ret_cxx) ret_cxx = "double";
        fputs("extern \"C\" ", out);
        fprintf(out, "%s %s(", ret_cxx, fn->name ? fn->name : "_anon");
        int aidx = 0;
        for (const KflcNode *a = fn->children; a; a = a->next) {
            if (a->kind != KFLN_FN_ARG) continue;
            if (aidx > 0) fputs(", ", out);
            const char *aty = kflc_type_cxx(a->type, a->type_subtype);
            fprintf(out, "%s %s", aty ? aty : "double",
                    a->name ? a->name : "_a");
            aidx++;
        }
        if (aidx == 0) fputs("void", out);
        fputs(") {\n", out);

        KflcExprBinding *live = NULL;
        int live_n = 0, live_cap = 0;
        for (const KflcNode *a = fn->children; a; a = a->next) {
            if (a->kind != KFLN_FN_ARG) continue;
            rl_push_binding(arena, &live, &live_n, &live_cap,
                             a->name, a->type);
            live[live_n - 1].type_subtype = a->type_subtype;
            live[live_n - 1].lifetime_qualifier = a->lifetime_qualifier;
        }
        for (const KflcNode *s = fn->children; s; s = s->next) {
            if (s->kind == KFLN_FN_ARG) continue;
            rl_collect_lets(s, arena, &live, &live_n, &live_cap);
        }
        rl_collect_form_args(form, arena, &live, &live_n, &live_cap);

        KflcExprCtx body_ctx;
        memset(&body_ctx, 0, sizeof body_ctx);
        body_ctx.bindings   = live;
        body_ctx.n_bindings = live_n;
        body_ctx.fns        = user_fn_arr;
        body_ctx.n_fns      = n_user_fns;
        body_ctx.form       = form;

        kfl_emit_stmt_reset_scopes_ex(arena, fn->type, fn->type_subtype);
        int last_was_return = 0;
        for (const KflcNode *s = fn->children; s; s = s->next) {
            if (s->kind == KFLN_FN_ARG) continue;
            last_was_return = (s->kind == KFLN_STMT_RETURN);
            (void)kfl_emit_stmt(out, s, &body_ctx, diag, 4);
        }
        if (!last_was_return) kfl_emit_stmt_drain_root(out, 4);
        fputs("}\n\n", out);
    }
    return diag->errors ? 1 : 0;
}

/* Program parameters evaluated over form arguments at create. */

int rl_emit_params(FILE *out, const RlModel *m,
                           const KflcExprCtx *arg_ctx, KflcDiag *diag)
{
    fputs("static double kflrl_control_dt_(void)\n{\n    return (double)(",
          out);
    if (kflc_emit_expr(out, m->control_dt->expr, arg_ctx, diag)) return 1;
    fputs(");\n}\n\n", out);

    /* The subdivision of a control period. Emitted as an accessor
     * beside the horizon, for the horizon's reason: it is a declared
     * expression, and create is where a declared value is read and
     * checked once. */
    fputs("static uint32_t kflrl_substeps_(void)\n{\n    return (uint32_t)(",
          out);
    if (m->substeps && m->substeps->expr) {
        if (kflc_emit_expr(out, m->substeps->expr, arg_ctx, diag)) return 1;
    } else {
        fputs("1", out);
    }
    fputs(");\n}\n\n", out);

    /* The contact resolution and, for bounce, its two coefficients.
     * Emitted as accessors for the same reason as the subdivision:
     * they are declared expressions, and create is where a declared
     * value is read once. A program that declares no `contact` line
     * gets arrest, which is the default the design fixes, so the
     * absent case and the `contact arrest` case emit the same
     * artifact. */
    {
        int bounce = m->contact_kind &&
                     m->contact_kind->value.kind == KFLV_IDENT &&
                     m->contact_kind->value.u.s &&
                     strcmp(m->contact_kind->value.u.s, "bounce") == 0;
        fprintf(out, "#define KFLRL_CONTACT_BOUNCE %d\n\n", bounce ? 1 : 0);
        fputs("static double kflrl_restitution_(void)\n{\n    return (",
              out);
        if (bounce && m->restitution && m->restitution->expr) {
            if (kflc_emit_expr(out, m->restitution->expr, arg_ctx, diag)) {
                return 1;
            }
        } else {
            fputs("0.0", out);
        }
        fputs(");\n}\n\n", out);
        fputs("static double kflrl_friction_(void)\n{\n    return (", out);
        if (bounce && m->friction && m->friction->expr) {
            if (kflc_emit_expr(out, m->friction->expr, arg_ctx, diag)) {
                return 1;
            }
        } else {
            fputs("0.0", out);
        }
        fputs(");\n}\n\n", out);
    }

    fputs("static uint32_t kflrl_horizon_(void)\n{\n    return (uint32_t)(",
          out);
    if (m->horizon && m->horizon->expr) {
        if (kflc_emit_expr(out, m->horizon->expr, arg_ctx, diag)) return 1;
    } else {
        fputs("0", out);
    }
    fputs(");\n}\n\n", out);

    /* Action channel parameters: bounds, kinds, arities, defaults.
     * Discrete channels publish bounds 0 to arity - 1 so a consumer
     * reading only the bounds tag still sees the legal range. */
    fputs("static void kflrl_act_params_(double *lo, double *hi,\n"
          "                              uint32_t *arity, uint16_t *kind)\n"
          "{\n"
          "    (void)lo; (void)hi; (void)arity; (void)kind;\n", out);
    for (int i = 0; i < m->n_actions; i++) {
        const KflcNode *a = m->actions[i];
        int is_box = (a->position.kind == KFLV_IDENT && a->position.u.s &&
                      strcmp(a->position.u.s, "box") == 0);
        if (is_box) {
            fprintf(out, "    kind[%d] = K26RL_ACT_KIND_BOX; "
                         "arity[%d] = 0;\n", i, i);
            fprintf(out, "    lo[%d] = (double)(", i);
            if (kflc_emit_expr(out, a->expr, arg_ctx, diag)) return 1;
            fputs(");\n", out);
            fprintf(out, "    hi[%d] = (double)(", i);
            if (kflc_emit_expr(out, a->expr2, arg_ctx, diag)) return 1;
            fputs(");\n", out);
        } else {
            fprintf(out, "    kind[%d] = K26RL_ACT_KIND_DISCRETE;\n", i);
            fprintf(out, "    arity[%d] = (uint32_t)(", i);
            if (kflc_emit_expr(out, a->expr, arg_ctx, diag)) return 1;
            fputs(");\n", out);
            fprintf(out, "    lo[%d] = 0.0;\n", i);
            fprintf(out, "    hi[%d] = (double)(arity[%d] > 0 ? "
                         "arity[%d] - 1 : 0);\n", i, i, i);
        }
    }
    fputs("}\n\n", out);

    /* Batch-mode action defaults: every channel holds its declared
     * default for the whole run (0 for box, choice 0 for discrete,
     * when no default is declared). */
    fputs("static void kflrl_act_defaults_(double *out_v)\n"
          "{\n"
          "    (void)out_v;\n", out);
    for (int i = 0; i < m->n_actions; i++) {
        const KflcAttr *d = rl_attr(m->actions[i], "default");
        fprintf(out, "    out_v[%d] = (double)(", i);
        if (d && d->expr) {
            if (kflc_emit_expr(out, d->expr, arg_ctx, diag)) return 1;
        } else {
            fputs("0", out);
        }
        fputs(");\n", out);
    }
    fputs("}\n\n", out);
    return 0;
}

/* World construction: the fn world prefix statements in source order.
 * astro_body declarations are emitted here (with the six scalar state
 * keys mapped onto the compound fields and distribution values drawn
 * at the environment's episode-0 coordinates); reinforcement learning
 * constructs and as-bound observes are the episode machinery's and
 * are skipped; everything else is the ordinary statement emitter. */

/* Construct every declared payload, once per environment, in the world
 * prefix and after the vehicles exist.
 *
 * This is the whole of the tier's allocation discipline on this side:
 * the constructors and destructors are the only allocating functions
 * the five libraries have, and they are called here and at teardown.
 * The evaluators the step calls allocate nothing and return a value
 * struct, so nothing below this function has to be counted.
 *
 * The declared parameters are also stored per environment, because the
 * tier's handles publish no accessors for them and the evaluators take
 * them as arguments. That store is what a per-episode draw writes, so
 * a randomised parameter reaches the evaluator on the episode that
 * drew it. */

static int rl_emit_payload_build_(FILE *out, const RlModel *m,
                                  const KflcExprCtx *ctx, KflcDiag *diag)
{
    for (int p = 0; p < m->n_payloads; p++) {
        const RlPayload *py = &m->payloads[p];
        const RlPayKindDesc *kd = &RL_PAY_KIND_[py->kind];
        fprintf(out, "    {\n"
                     "        /* astro_payload `%s`, kind `%s`, carried "
                     "by `%s` */\n"
                     "        double *_kfl_pp = _kfl_payp + %d * "
                     "KFLRL_PAY_NPARAM;\n",
                py->name, kd->name, m->bodies[py->body].body->name, p);
        for (int k = 0; k < kd->n_keys; k++) {
            if (py->dr[k] >= 0) {
                fputs("        {\n            double _kfl_v = ", out);
                if (rl_emit_draw(out, py->dist[k], 0x0002u,
                                  m->dr[py->dr[k]].channel, ctx, diag)) {
                    return 1;
                }
                fputs(";\n", out);
                fprintf(out, "            if (_kfl_dr0) _kfl_dr0[%d] = "
                             "_kfl_v;\n", py->dr[k]);
                fprintf(out, "            _kfl_pp[%d] = _kfl_v;\n", k);
                fputs("        }\n", out);
            } else if (kd->keys[k].words) {
                /* A keyword-valued key stores the library constant the
                 * declared word names, so the store carries one number
                 * per key however the key was spelled and the
                 * constructor call below indexes it like any other. */
                const char *v = py->attr[k] ? rl_pay_attr_text(py->attr[k])
                                            : NULL;
                const char *code = NULL;
                for (int w = 0; w < kd->keys[k].n_words; w++) {
                    if (v && strcmp(kd->keys[k].words[w].word, v) == 0) {
                        code = kd->keys[k].words[w].code;
                    }
                }
                fprintf(out, "        _kfl_pp[%d] = (double)(%s);\n",
                        k, code ? code : kd->keys[k].dflt);
            } else if (kd->keys[k].ident) {
                /* An open identifier names another declaration or a
                 * community of them, and the compiler has already
                 * resolved it into a table beside this store. The slot
                 * is kept and zeroed so a kind's store has one shape
                 * whatever its keys are. */
                fprintf(out, "        _kfl_pp[%d] = 0.0;\n", k);
            } else {
                const char *v = py->attr[k] ? rl_pay_attr_text(py->attr[k])
                                            : kd->keys[k].dflt;
                fprintf(out, "        _kfl_pp[%d] = (double)(%s);\n",
                        k, v ? v : kd->keys[k].dflt);
            }
        }
        if (kd->is_link) {
            /* Nothing to construct. The datalink takes no slot of the
             * tier, so the handle array's entry stays null and the
             * transfer pass reads this store and the link tables
             * instead. */
            fprintf(out, "        _kfl_pay[%d] = NULL;\n"
                         "    }\n", p);
            continue;
        }
        fprintf(out,
            "        K26AstroVehicle *_kfl_ov = _kfl_veh ? _kfl_veh[%d] "
            ": NULL;\n"
            "        if (!_kfl_ov) return -1;\n", py->veh);
        if (py->kind == RL_PAY_INFOSTATE) {
            fputs(
            "        K26AstroInfostate *_kfl_h = k26astro_infostate_new(\n"
            "            _kfl_ov, (int)_kfl_pp[0]);\n"
            "        if (!_kfl_h) return -1;\n"
            "        if (k26astro_infostate_attach(_kfl_h) != 0) {\n"
            "            k26astro_infostate_destroy(_kfl_h);\n"
            "            return -1;\n"
            "        }\n", out);
        } else if (py->kind == RL_PAY_IMPACTOR) {
            /* The constructor takes the pattern, the three projectile
             * parameters and the two swarm ones; the ten target
             * parameters sit above them in the store and are read by
             * the impact analysis at engagement. A single-pattern
             * payload passes the library's own ignored values for the
             * two swarm arguments, which its header names as ignored
             * for that pattern. */
            fputs(
            "        K26AstroImpactor *_kfl_h = k26astro_impactor_new(\n"
            "            (K26AstroImpactorPattern)(int)_kfl_pp[0],\n"
            "            _kfl_pp[1], _kfl_pp[2], _kfl_pp[3],\n"
            "            (int)_kfl_pp[4], _kfl_pp[5]);\n"
            "        if (!_kfl_h) return -1;\n"
            "        if (k26astro_impactor_bind(_kfl_h, _kfl_ov) != 0) {\n"
            "            k26astro_impactor_destroy(_kfl_h);\n"
            "            return -1;\n"
            "        }\n", out);
            /* A swarm's declared projectile mass is the total released
             * mass, which the swarm library's own per-unit helper says
             * plainly: it divides that total by the count. So the
             * declared projectile describes the release and not a
             * unit, and the question the penetration analysis answers,
             * whether an arriving projectile gets through this shield,
             * is a question about a unit.
             *
             * A second handle carries that unit. Its mass is the
             * per-unit mass the library computes; its diameter is
             * scaled by the cube root of the count, which is what
             * divides a body into geometrically similar pieces; and
             * its density is unchanged, which is what makes the three
             * agree. Deriving one of the three from the other two
             * instead would silently overrule whatever relation the
             * program declared, and this library accepts all three
             * independently.
             *
             * It is built here, in the world prefix, and it binds to
             * no vehicle: it is a description of a shape rather than a
             * payload the craft carries. */
            if (py->attr[0] &&
                rl_pay_attr_text(py->attr[0]) &&
                strcmp(rl_pay_attr_text(py->attr[0]), "swarm") == 0) {
                fputs(
                "        {\n"
                "            double _kfl_um = k26astro_swarm_per_unit_mass(\n"
                "                (int)_kfl_pp[4], _kfl_pp[1]);\n"
                "            double _kfl_ud = (_kfl_pp[4] > 0.0)\n"
                "                ? _kfl_pp[3] / cbrt(_kfl_pp[4]) : _kfl_pp[3];\n"
                "            K26AstroImpactor *_kfl_hu =\n"
                "                k26astro_impactor_new(\n"
                "                    K26ASTRO_IMPACTOR_PATTERN_SINGLE,\n"
                "                    _kfl_um, _kfl_pp[2], _kfl_ud, 1, 0.0);\n"
                "            if (!_kfl_hu) {\n"
                "                k26astro_impactor_destroy(_kfl_h);\n"
                "                return -1;\n"
                "            }\n", out);
                fprintf(out,
                "            _kfl_payu[%d] = (void *)_kfl_hu;\n"
                "        }\n", p);
            }
        } else if (py->kind == RL_PAY_LASER) {
            /* The constructor takes the seven emitter parameters; the
             * material and the reflectivity describe the target and are
             * read by the evaluator at engagement. */
            fputs(
            "        K26AstroLaser *_kfl_h = k26astro_laser_new(\n"
            "            _kfl_pp[0], _kfl_pp[1], _kfl_pp[2], _kfl_pp[3],\n"
            "            _kfl_pp[4], _kfl_pp[5], _kfl_pp[6]);\n"
            "        if (!_kfl_h) return -1;\n"
            "        if (k26astro_laser_bind(_kfl_h, _kfl_ov) != 0) {\n"
            "            k26astro_laser_destroy(_kfl_h);\n"
            "            return -1;\n"
            "        }\n", out);
        } else if (py->kind == RL_PAY_DECOY) {
            /* The constructor takes all six keys: the modality, the
             * mass and separation the deploy costs its host, and the
             * three match qualities the discrimination dispatch
             * couples with the observer's regime. */
            fputs(
            "        K26AstroDecoy *_kfl_h = k26astro_decoy_new(\n"
            "            (K26AstroDecoyMode)(int)_kfl_pp[0],\n"
            "            _kfl_pp[1], _kfl_pp[2], _kfl_pp[3],\n"
            "            _kfl_pp[4], _kfl_pp[5]);\n"
            "        if (!_kfl_h) return -1;\n"
            "        if (k26astro_decoy_bind(_kfl_h, _kfl_ov) != 0) {\n"
            "            k26astro_decoy_destroy(_kfl_h);\n"
            "            return -1;\n"
            "        }\n", out);
        } else if (py->kind == RL_PAY_JAMMER) {
            /* The constructor takes the first six keys; the radiator
             * temperature sits above them in the store and is read by
             * the counter-detection routine at engagement. */
            fputs(
            "        K26AstroJammer *_kfl_h = k26astro_jammer_new(\n"
            "            (K26AstroJammerMode)(int)_kfl_pp[0],\n"
            "            _kfl_pp[1], _kfl_pp[2], _kfl_pp[3],\n"
            "            _kfl_pp[4], _kfl_pp[5]);\n"
            "        if (!_kfl_h) return -1;\n"
            "        if (k26astro_jammer_bind(_kfl_h, _kfl_ov) != 0) {\n"
            "            k26astro_jammer_destroy(_kfl_h);\n"
            "            return -1;\n"
            "        }\n", out);
        } else {
            const char *fn =
                py->kind == RL_PAY_DETECT_IR    ? "k26astro_detect_sensor_new_ir"
              : py->kind == RL_PAY_DETECT_RADAR ? "k26astro_detect_sensor_new_radar"
                                                : "k26astro_detect_sensor_new_lidar";
            /* The constructor takes only the instrument's own
             * parameters; the target-class ones sit above them in the
             * store and are read by the evaluator. */
            int n_ctor = py->kind == RL_PAY_DETECT_IR    ? 6
                       : py->kind == RL_PAY_DETECT_RADAR ? 9 : 6;
            fprintf(out,
                "        K26AstroDetectSensor *_kfl_h = %s(\n", fn);
            for (int k = 0; k < n_ctor; k++) {
                fprintf(out, "            _kfl_pp[%d]%s\n", k,
                        k + 1 == n_ctor ? ");" : ",");
            }
            fputs(
            "        if (!_kfl_h) return -1;\n"
            "        if (k26astro_detect_sensor_attach(_kfl_h, _kfl_ov) "
            "!= 0) {\n"
            "            k26astro_detect_sensor_destroy(_kfl_h);\n"
            "            return -1;\n"
            "        }\n", out);
        }
        /* The kind tag the payload carries is checked against the tag
         * this program wrote from the registry, so the grammar's claim
         * to mirror that registry is measured rather than asserted. */
        fprintf(out,
            "        if (k26astro_payload_kind("
            "(const K26AstroPayload *)_kfl_h) != kflrl_pay_tag_[%d]) {\n",
            p);
        fprintf(out, "            %s(_kfl_h);\n            return -1;\n"
                     "        }\n", rl_pay_dtor(py->kind));
        fprintf(out, "        _kfl_pay[%d] = (void *)_kfl_h;\n"
                     "    }\n", p);
    }
    return 0;
}

int rl_emit_build_world(FILE *out, const RlModel *m,
                                const KflcNode *form, KflcArena *arena,
                                KflcExprFn *user_fn_arr, int n_user_fns,
                                KflcDiag *diag)
{
    fputs("static int kflrl_build_world_(K26AstroWorld *world, "
          "K26RngKey _kfl_key,\n"
          "                              uint32_t _kfl_envi, "
          "double *_kfl_wscal,\n"
          "                              double *_kfl_dr0,\n"
          "                              K26AstroVehicle **_kfl_veh,\n"
          "                              void **_kfl_pay, "
          "void **_kfl_payu,\n"
          "                              double *_kfl_payp)\n"
          "{\n"
          "    const uint32_t _kfl_ep = 0;\n"
          "    (void)_kfl_key; (void)_kfl_envi; (void)_kfl_ep; "
          "(void)_kfl_wscal; (void)_kfl_dr0; (void)_kfl_veh;\n"
          "    (void)_kfl_pay; (void)_kfl_payu; (void)_kfl_payp;\n", out);

    /* Known-body index locals, the batch emitter's convention, so the
     * shared statement emitter resolves parent/observe targets. A
     * name declared twice shares one local, as the batch emitter's
     * dedup does. */
    for (int i = 0; i < m->n_bodies; i++) {
        const char *bn = m->bodies[i].body->name;
        int dup = 0;
        for (int j = 0; j < i; j++) {
            const char *pn = m->bodies[j].body->name;
            if (pn && strcmp(pn, bn) == 0) dup = 1;
        }
        if (dup) continue;
        fprintf(out, "    int _kfl_body_%s_idx = -1; "
                     "(void)_kfl_body_%s_idx;\n", bn, bn);
    }

    /* Binding table: form args, prefix lets, and the world handle. */
    KflcExprBinding *live = NULL;
    int live_n = 0, live_cap = 0;
    rl_collect_form_args(form, arena, &live, &live_n, &live_cap);
    for (const KflcNode *s = m->world->children; s; s = s->next) {
        if (s->kind == KFLN_STMT_EPISODE || s->kind == KFLN_STMT_ACTION ||
            s->kind == KFLN_STMT_ON_STEP || s->kind == KFLN_STMT_OBJECTIVE ||
            s->kind == KFLN_STMT_AGENT ||
            s->kind == KFLN_STMT_ASTRO_PAYLOAD ||
            s->kind == KFLN_STMT_CAPTURE_ENVELOPE) {
            continue;
        }
        rl_collect_lets(s, arena, &live, &live_n, &live_cap);
    }
    rl_push_binding(arena, &live, &live_n, &live_cap, "world",
                     KFLT_OPAQUE);
    live[live_n - 1].type_subtype = "world";

    const char *known[RL_MAX_BODIES];
    int n_known = 0;
    for (int i = 0; i < m->n_bodies; i++) {
        const char *bn = m->bodies[i].body->name;
        int dup = 0;
        for (int j = 0; j < n_known; j++) {
            if (bn && strcmp(known[j], bn) == 0) dup = 1;
        }
        if (bn && !dup) known[n_known++] = bn;
    }

    KflcExprCtx ctx;
    memset(&ctx, 0, sizeof ctx);
    ctx.bindings           = live;
    ctx.n_bindings         = live_n;
    ctx.fns                = user_fn_arr;
    ctx.n_fns              = n_user_fns;
    ctx.known_body_names   = known;
    ctx.n_known_body_names = n_known;
    ctx.form               = form;
    ctx.headless           = 1;

    kfl_emit_stmt_reset_scopes(arena, KFLT_VOID);

    int body_i = 0;
    int veh_i  = 0;
    RlVehEmit veh[RL_MAX_VEH];
    for (const KflcNode *s = m->world->children; s; s = s->next) {
        switch (s->kind) {
        case KFLN_STMT_EPISODE:
        case KFLN_STMT_ACTION:
        case KFLN_STMT_ON_STEP:
        case KFLN_STMT_OBJECTIVE:
        case KFLN_STMT_SENSOR:
        case KFLN_STMT_AGENT:
        /* Payloads are constructed after the vehicles exist, so the
         * statement contributes nothing where it is written. */
        case KFLN_STMT_ASTRO_PAYLOAD:
        /* A plan block declares an action space and a destination for
         * what that space produces; it builds nothing in the world. */
        case KFLN_STMT_PLAN:
        /* A declared capture envelope is a set of compile-time
         * constants already folded into the ports that name it, so
         * the block builds nothing here either. */
        case KFLN_STMT_CAPTURE_ENVELOPE:
            continue;
        case KFLN_STMT_OBSERVE:
            if (rl_observe_as(s)) continue;   /* channel, not a print */
            (void)kfl_emit_stmt(out, s, &ctx, diag, 4);
            continue;
        case KFLN_STMT_ASTRO_BODY: {
            /* The binding's rules and its numbers come from the one
             * resolver, so this emitter and the batch one cannot
             * disagree about what an assembly means. */
            KflcAssembly *asmb  = NULL;
            KflcArena    *asm_a = kflc_arena_create();
            if (!asm_a) return 1;
            if (kflc_assembly_for_body(s, diag->path, asm_a, diag, &asmb)) {
                kflc_arena_release(asm_a);
                return 1;
            }
            fputs("    {\n"
                  "        K26AstroBody _kfl_b; "
                  "k26astro_body_init(&_kfl_b);\n", out);
            fprintf(out,
                "        snprintf(_kfl_b.name, sizeof _kfl_b.name, "
                "\"%%s\", \"%s\");\n", s->name ? s->name : "_anon");
            if (asmb) {
                char hex[2 * KFLC_ASM_DIGEST + 1];
                kflc_assembly_digest_hex(asmb->digest, hex);
                fprintf(out, "        /* assembly `%s`, digest %s */\n",
                        asmb->name, hex);
                if (asmb->propellant >= 0) {
                    fprintf(out,
                        "        kflrl_apply_props_(NULL, &_kfl_b, %d, "
                        "%.17g, NULL);\n", veh_i, asmb->prop_capacity);
                } else {
                    fprintf(out,
                        "        k26astro_body_set_mass(&_kfl_b, %.17g);\n",
                        asmb->mass);
                }
                fprintf(out,
                        "        static const double _kfl_asm_com[3] = "
                        "{ %.17g, %.17g, %.17g };\n",
                        asmb->com[0], asmb->com[1], asmb->com[2]);
                fprintf(out,
                        "        static const double _kfl_asm_inertia[6] = "
                        "{ %.17g, %.17g, %.17g, %.17g, %.17g, %.17g };\n",
                        asmb->inertia[0], asmb->inertia[1], asmb->inertia[2],
                        asmb->inertia[3], asmb->inertia[4], asmb->inertia[5]);
                fputs("        (void)_kfl_asm_com; (void)_kfl_asm_inertia;\n",
                      out);
            }
            for (const KflcAttr *a = s->attrs; a; a = a->next) {
                if (!a->name) continue;
                if (strcmp(a->name, "assembly") == 0) continue;
                if (strcmp(a->name, "reference") == 0) continue;
                const char *val =
                    (a->value.kind == KFLV_IDENT && a->value.u.s)
                    ? a->value.u.s : "0";
                if (strcmp(a->name, "parent") == 0) {
                    if (rl_body_index_of(m, val) >= 0) {
                        fprintf(out, "        _kfl_b.parent_body_idx = "
                                     "_kfl_body_%s_idx;\n", val);
                    } else {
                        fprintf(out, "        _kfl_b.parent_body_idx = "
                                     "k26astro_world_find_body(world, "
                                     "\"%s\");\n", val);
                    }
                    continue;
                }
                /* Distribution-valued attribute: episode-0 draw at
                 * this parameter's coordinates, the coordinate's only
                 * consumption at create; the value is handed out
                 * through _kfl_dr0 so kflrl_apply_draws_ records it
                 * without re-drawing. */
                int dr_slot = -1;
                for (int d = 0; d < m->n_dr; d++) {
                    if (m->dr[d].attr == a) dr_slot = d;
                }
                if (dr_slot >= 0) {
                    fputs("        {\n            double _kfl_v = ", out);
                    if (rl_emit_draw(out, m->dr[dr_slot].dist, 0x0002u,
                                      m->dr[dr_slot].channel, &ctx, diag)) {
                        return 1;
                    }
                    fputs(";\n", out);
                    fprintf(out, "            if (_kfl_dr0) "
                                 "_kfl_dr0[%d] = _kfl_v;\n", dr_slot);
                    rl_emit_body_write_var(out, 12, "_kfl_b.", a->name,
                                            "_kfl_v");
                    fputs("        }\n", out);
                } else {
                    rl_emit_body_write(out, 8, "_kfl_b.", a->name, val);
                }
            }
            fprintf(out,
                "        _kfl_body_%s_idx = "
                "k26astro_world_add_body(world, _kfl_b);\n"
                "        if (_kfl_body_%s_idx < 0) return -1;\n"
                "        kflrl_body_idx_[%d] = _kfl_body_%s_idx;\n",
                s->name, s->name, body_i, s->name);
            if (asmb) {
                if (veh_i >= RL_MAX_VEH) {
                    kflc_diag_errorf(diag, s->line,
                        "more than %d bodies carry an assembly",
                        RL_MAX_VEH);
                    kflc_arena_release(asm_a);
                    return 1;
                }
                veh[veh_i].body_name = s->name;
                veh[veh_i].mass      = asmb->mass;
                veh[veh_i].has_prop  = asmb->propellant >= 0;
                veh[veh_i].prop_cap  = asmb->prop_capacity;
                memcpy(veh[veh_i].com, asmb->com, sizeof veh[veh_i].com);
                memcpy(veh[veh_i].inertia, asmb->inertia,
                       sizeof veh[veh_i].inertia);
                veh_i++;
            }
            fputs("    }\n", out);
            kflc_arena_release(asm_a);
            body_i++;
            continue;
        }
        default:
            (void)kfl_emit_stmt(out, s, &ctx, diag, 4);
            continue;
        }
    }
    kfl_emit_stmt_drain_root(out, 4);

    /* The vehicles, after the last body has been added. Each carries
     * the derived inertia tensor and the centre-of-mass offset, and
     * binds the body the world now owns; the bind is only valid here,
     * for the reason RlVehEmit states. The world's registry is
     * non-owning, so the handle owns the vehicle and destroys it; this
     * is the one place that knows both when a world appears and when
     * it goes. Slot order is body declaration order, which is the
     * order every per-vehicle table in this artifact is written in. */
    for (int i = 0; i < veh_i; i++) {
        const RlVehEmit *ve = &veh[i];
        fputs("    {\n"
              "        K26AstroVehicle *_kfl_v = k26astro_vehicle_new();\n"
              "        if (!_kfl_v) return -1;\n", out);
        if (ve->has_prop) {
            fprintf(out,
                "        kflrl_apply_props_(_kfl_v, NULL, %d, %.17g, "
                "NULL);\n", i, ve->prop_cap);
        } else {
            fprintf(out,
                "        k26astro_vehicle_set_dry_mass(_kfl_v, %.17g);\n"
                "        k26astro_vehicle_set_com_offset(_kfl_v, "
                "%.17g, %.17g, %.17g);\n",
                    ve->mass, ve->com[0], ve->com[1], ve->com[2]);
            fprintf(out,
                "        K26M3 _kfl_I;\n"
                "        _kfl_I.m[0][0] = %.17g; _kfl_I.m[0][1] = %.17g; "
                "_kfl_I.m[0][2] = %.17g;\n"
                "        _kfl_I.m[1][0] = %.17g; _kfl_I.m[1][1] = %.17g; "
                "_kfl_I.m[1][2] = %.17g;\n"
                "        _kfl_I.m[2][0] = %.17g; _kfl_I.m[2][1] = %.17g; "
                "_kfl_I.m[2][2] = %.17g;\n"
                "        k26astro_vehicle_set_inertia_full(_kfl_v, "
                "_kfl_I);\n",
                    ve->inertia[0], ve->inertia[3], ve->inertia[4],
                    ve->inertia[3], ve->inertia[1], ve->inertia[5],
                    ve->inertia[4], ve->inertia[5], ve->inertia[2]);
        }
        fprintf(out,
            "        k26astro_vehicle_bind_body(_kfl_v, "
            "k26astro_world_body_at(world, _kfl_body_%s_idx));\n"
            "        if (k26astro_world_register_vehicle(world, "
            "_kfl_v) != 0) {\n"
            "            k26astro_vehicle_destroy(_kfl_v);\n"
            "            return -1;\n"
            "        }\n"
            "        if (_kfl_veh) _kfl_veh[%d] = _kfl_v;\n"
            "    }\n",
                ve->body_name, i);
    }

    if (rl_emit_payload_build_(out, m, &ctx, diag)) return 1;

    /* Capture the world scalars for the objective and termination
     * evaluators: the prefix runs once per environment at create, and
     * these are its final values. */
    for (int i = 0; i < m->n_wscal; i++) {
        fprintf(out, "    _kfl_wscal[%d] = (double)(%s);\n",
                i, m->wscal[i]->name);
    }
    fputs("    return 0;\n}\n\n", out);
    return diag->errors ? 1 : 0;
}

/* Per-episode draws: every drawn parameter is computed first into the
 * record slots (ascending tag order), then applied, attribute draws
 * before reset lines so a reset line targeting the same field wins,
 * as initial state overrides the built value. */

int rl_emit_apply_draws(FILE *out, const RlModel *m,
                                const KflcExprCtx *arg_ctx, KflcDiag *diag)
{
    fputs("static void kflrl_apply_draws_(K26AstroWorld *world, "
          "K26RngKey _kfl_key,\n"
          "                               uint32_t _kfl_envi, "
          "uint32_t _kfl_ep,\n"
          "                               double *rec,\n"
          "                               const double *_kfl_dr0,\n"
          "                               double *_kfl_payp)\n"
          "{\n"
          "    (void)world; (void)_kfl_key; (void)_kfl_envi; "
          "(void)_kfl_ep; (void)rec; (void)_kfl_dr0;\n"
          "    (void)_kfl_payp;\n", out);

    for (int i = 0; i < m->n_resets; i++) {
        fprintf(out, "    rec[%d] = ", i);
        if (rl_emit_draw(out, m->resets[i]->expr, 0x0001u, i,
                          arg_ctx, diag)) {
            return 1;
        }
        fputs(";\n", out);
    }
    /* At create the attribute draws were consumed while the world was
     * built; _kfl_dr0 hands their values in so each (seed, coordinate)
     * pair is drawn exactly once per handle. Boundary resets pass
     * null and draw at the new episode index. */
    for (int i = 0; i < m->n_dr; i++) {
        fprintf(out, "    rec[%d] = _kfl_dr0 ? _kfl_dr0[%d] : (",
                m->n_resets + i, i);
        if (rl_emit_draw(out, m->dr[i].dist, 0x0002u, m->dr[i].channel,
                          arg_ctx, diag)) {
            return 1;
        }
        fputs(");\n", out);
    }

    for (int i = 0; i < m->n_dr; i++) {
        char var[32];
        snprintf(var, sizeof var, "rec[%d]", m->n_resets + i);
        if (m->dr[i].payload >= 0) {
            /* A payload key's draw lands in the per-environment
             * parameter store, which is what the evaluators read: the
             * handle itself carries the values it was constructed
             * with and publishes no way to change them. */
            fprintf(out, "    _kfl_payp[%d * KFLRL_PAY_NPARAM + %d] = "
                         "%s;\n",
                    m->dr[i].payload, m->dr[i].param, var);
            continue;
        }
        fprintf(out, "    {\n        K26AstroBody *_kfl_bp = "
                     "k26astro_world_body_at(world, kflrl_body_idx_[%d]);\n"
                     "        if (_kfl_bp) {\n", m->dr[i].body);
        rl_emit_body_write_var(out, 12, "_kfl_bp->", m->dr[i].attr->name,
                                var);
        fputs("        }\n    }\n", out);
    }
    for (int i = 0; i < m->n_resets; i++) {
        const KflcNode *r = m->resets[i];
        int bidx = rl_body_index_of(m, r->name);
        const char *key = (r->position.kind == KFLV_IDENT)
                          ? r->position.u.s : NULL;
        if (bidx < 0 || !key) continue;   /* reported at collect */
        char var[32];
        snprintf(var, sizeof var, "rec[%d]", i);
        fprintf(out, "    {\n        K26AstroBody *_kfl_bp = "
                     "k26astro_world_body_at(world, kflrl_body_idx_[%d]);\n"
                     "        if (_kfl_bp) {\n", bidx);
        rl_emit_body_write_var(out, 12, "_kfl_bp->", key, var);
        fputs("        }\n    }\n", out);
    }
    fputs("}\n\n", out);
    return 0;
}
