/* text_to_header.c - carry a template file into a C header.
 *
 * Usage: text_to_header IN OUT NAME
 *
 * Reads IN, removes each line that starts with "#@" (an author note
 * kept beside the code it describes, never emitted), and writes OUT
 * as one static const char array called NAME holding the remaining
 * bytes with a final NUL. The array is bytes, not a string literal,
 * so no escaping can change what the emitter writes.
 *
 * Exit: 0 on success, 1 on any failure.
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int main(int argc, char **argv)
{
    if (argc != 4) {
        fprintf(stderr, "usage: %s IN OUT NAME\n", argv[0]);
        return 1;
    }
    FILE *in = fopen(argv[1], "rb");
    if (!in) {
        fprintf(stderr, "%s: cannot read %s\n", argv[0], argv[1]);
        return 1;
    }
    FILE *out = fopen(argv[2], "w");
    if (!out) {
        fprintf(stderr, "%s: cannot write %s\n", argv[0], argv[2]);
        fclose(in);
        return 1;
    }
    fprintf(out, "/* Generated by text_to_header from %s; do not "
                 "edit. */\n", argv[1]);
    fprintf(out, "static const char %s[] = {\n", argv[3]);
    /* One byte at a time, judging the note marker at the start of
     * each line rather than of each buffer, so a long line cannot
     * split the test and no byte value ends a read early. */
    int col = 0;
    int at_line_start = 1;
    int in_note = 0;
    int c;
    while ((c = fgetc(in)) != EOF) {
        if (at_line_start) {
            in_note = 0;
            if (c == '#') {
                int c2 = fgetc(in);
                if (c2 == '@') {
                    in_note = 1;
                } else {
                    fprintf(out, "%d,", '#');
                    if (++col % 20 == 0)
                        fputc('\n', out);
                    if (c2 == EOF)
                        break;
                    ungetc(c2, in);
                }
                at_line_start = 0;
                if (in_note)
                    continue;
                continue;
            }
        }
        at_line_start = (c == '\n');
        if (in_note)
            continue;
        fprintf(out, "%d,", c);
        if (++col % 20 == 0)
            fputc('\n', out);
    }
    if (ferror(in)) {
        fprintf(stderr, "%s: read error on %s\n", argv[0], argv[1]);
        fclose(in);
        fclose(out);
        remove(argv[2]);
        return 1;
    }
    fputs("0 };\n", out);
    fclose(in);
    if (fclose(out) != 0) {
        fprintf(stderr, "%s: cannot finish %s\n", argv[0], argv[2]);
        return 1;
    }
    return 0;
}
